### PR TITLE
Solving auto-deploy bug

### PR DESCRIPTION
**Pull request by alaxalves**
## Proposed changes
Adds a docker development environment and fixes wheel's build packaging

## Link to issue
Solves https://github.com/andre-filho/commit-helper/issues/68

## Other comments
I was able to deploy it. Available at https://pypi.org/project/commit-helper-testing/

### CODE REVIEW

**Comment by alaxalves** [comment]
@andre-filho I'm not sure if I was able to test it out properly. Could you test this and make sure this PR actually solves this?

**Comment by andre-filho** [comment]
It is not working. It is as follows:
image

**Comment by andre-filho** [comment]
I've figured what is wrong, tnx

**Comment by alaxalves** [comment]
@andre-filho How did you fix it?

**Comment by andre-filho** [comment]
I didn't, though I though I did.
Now it is deploying to pypi, but the still packaging is still not picking all the files
see error: 
image

**Comment by andre-filho** [comment]
Here is a better image:
image

**Pull request merged**
