### PR TITLE
Creates logo for commit-helper

### PR DESCRIPTION
**Pull request by MatheusRich**
## Proposed changes
Creates logo for commit-helper

## Screen-shot of changes
image

## Other comments
There are 3 options. From the left to the right on the screenshot:
1. With gradient
2. Without gradient
3. Without gradient and more "roundy"

Let me know which one do you prefer, so I can update de .svg file and add a png on README.md.

### CODE REVIEW

**Comment by andre-filho** [comment]
the third one, plz

**Comment by andre-filho** [comment]
and if you could send me version of the logo in the following dimensions, I would be glad:
- 2k x 2k px
- 200 x 200 px

**Comment by MatheusRich** [comment]
@andre-filho Here's the final version!
https://github.com/andre-filho/commit-helper/pull/27/files#diff-b369277853d13691e59d290ea8a826a2

**Comment by andre-filho** [comment]
@MatheusRich thnx

**Pull request merged**
